### ISSUE TITLE
GUI Issue 2 - End Game and Gameplay

### ISSUE THREAD

**Issue by santosty25** [v-rob/Carcassonne#10]
In a game of Carcassonne, there is a set number of tiles. However when the game ends, there is still a tile shown. That may be a bug considering that the tile may not have been used and if all the tiles have been used, it would be confusing if there is a tile in the deck. When the game ends, I suggest you write code to change the ImageView on the deck to show nothing. This would make it clearer that all the tiles in the deck have been used. Once done playing through the game, a pop up screen shows who won. When clicking ok, there is a tile still shown in the deck. You could write code in the checkIfGameOver method to change the ImageView before returning a String. The buttons and tiles could be spaced out more since the app sometimes doesn’t detect when I touched the tile. During the midgame, when I press on the top right corner of a tile near the button, nothing happens. This is a very minor bug that can be fixed easily.

**Comment by v-rob** [comment]
Fixed
