### ISSUE TITLE
GUI Issue 1

### ISSUE THREAD

**Issue by santosty25** [v-rob/Carcassonne#9]
Even though you can play with less than five players, the right side of the screen that shows the scoreboard still has five players listed. During the startup phase, if you only select four or less players and press start, the game will begin, but the names of the player’s aren’t updated on the right and there are still five players shown. If you were to get the player name from a String from the Human Player classes, you can update the right side of the screen depending on the amount of players. Also, in the XML layout file there are Meeples next to each player’s name that determines which color you are, but when the app is running that is missing. Something could be added to the GUI to determine whose turn it is because if multiple players had the same name and there is no indicator of whose turn it is, it may be confusing.

**Comment by v-rob** [comment]
Fixed.
